### PR TITLE
fix: flush batcher queue only when needed

### LINKED ISSUE #1510: fix: flush batcher queue only when needed

### PR DESCRIPTION
**Pull request by uri-99**
# Flush batcher queue only when necessary

> [!Note]
> This pr includes the content of #1507.

## Description

Modifies the batcher queue's behavior when encountering an error during task creation. Instead of flushing the entire queue by default, the logic now checks the error type. We only flush when the transaction reverted due to: 
- `SubmissionInsufficientBalance`
- `Generic`

## Type of change

Please delete options that are not relevant.

- [x] Bug fix

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

### CODE REVIEW

File: batcher/aligned-batcher/src/lib.rs [hunk 1]
```diff
@@ -1274,30 +1274,48 @@ impl Batcher {
...
 
-            self.flush_queue_and_clear_nonce_cache().await;
-
             return Err(e);
         };
 
         connection::send_batch_inclusion_data_responses(finalized_batch, &batch_merkle_tree).await
     }
 
+    async fn send_close_messages(
```
Comment (MarcosNicolau) [inline batcher/aligned-batcher/src/lib.rs]: I would rename this fn to something like `send_entries_task_creatior_error`.

File: batcher/aligned-batcher/src/lib.rs [hunk 2]
```diff
@@ -1274,30 +1274,48 @@ impl Batcher {
...
-                    warn!("Websocket sink was found empty. This should only happen in tests");
+
+            // decide if i want to flush the queue:
+            match e {
+                BatcherError::TransactionSendError(
+                    TransactionSendError::SubmissionInsufficientBalance,
+                )
+                | BatcherError::TransactionSendError(TransactionSendError::Generic(_)) => {
+                    self.flush_queue_and_clear_nonce_cache().await;
+                    self.send_close_messages(finalized_batch, batch_merkle_tree, &e)
```
Comment (avilagaston9) [inline batcher/aligned-batcher/src/lib.rs:1285]: The `flush_queue_and_clear_nonce_cache` method is already sending a `BatchReset` message and since we haven't remove the finalized proofs from the queue we are sending two messages to them.

File: batcher/aligned-batcher/src/lib.rs [hunk 3]
```diff
@@ -1274,30 +1274,48 @@ impl Batcher {
...
-                        SubmitProofResponseMessage::CreateNewTaskError(
-                            merkle_root,
-                            format!("{:?}", e),
-                        ),
-                    )
-                    .await
-                } else {
-                    warn!("Websocket sink was found empty. This should only happen in tests");
+
+            // decide if i want to flush the queue:
```
Comment (MarcosNicolau) [inline batcher/aligned-batcher/src/lib.rs:1316]:
```suggestion
```

**Review by MarcosNicolau — COMMENTED** [review]
Works alright, but we should merge it with #1507 as it is a dependency.

**Review by MarcosNicolau — APPROVED** [review]
Tested on macos, works as expected.

File: batcher/aligned-batcher/src/lib.rs (hunk 1 above)
Comment (uri-99) [reply batcher/aligned-batcher/src/lib.rs]: done

File: batcher/aligned-batcher/src/lib.rs (hunk 3 above)
Comment (uri-99) [reply batcher/aligned-batcher/src/lib.rs:1316]: code was put for making it easier to read

**Review by avilagaston9 — APPROVED** [review]
Works in my machine!

File: batcher/aligned-batcher/src/types/batch_queue.rs [hunk 4]
```diff
@@ -134,27 +134,25 @@ pub(crate) fn calculate_batch_size(batch_queue: &BatchQueue) -> Result<usize, Ba
 }
 
 /// This function tries to build a batch to be submitted to Aligned.
-/// Given a copy of the current batch queue, , and applyies an algorithm to find the biggest batch
+/// Given a COPY of the current batch queue, , and applyies an algorithm to find the biggest batch
```
Comment (Oppen) [inline batcher/aligned-batcher/src/types/batch_queue.rs]: Something seems to be missing here:
```
/// Given a COPY of the current batch queue, <???>, and applyies an algorithm to find the biggest batch
```

File: batcher/aligned-batcher/src/types/batch_queue.rs [hunk 5]
```diff
@@ -628,10 +612,9 @@ mod test {
         // The max batch len is 2, so the algorithm should stop at the second entry.
         let max_batch_proof_qty = 2;
 
-        let (resulting_batch_queue, finalized_batch) =
+        let finalized_batch =
             try_build_batch(batch_queue, gas_price, 5000000, max_batch_proof_qty).unwrap();
 
-        assert_eq!(resulting_batch_queue.len(), 1);
```
Comment (Oppen) [inline batcher/aligned-batcher/src/types/batch_queue.rs:634]: The test should probably assert the old queue remains the same size.

File: batcher/aligned-batcher/src/types/batch_queue.rs (hunk 4 above)
Comment (MarcosNicolau) [reply batcher/aligned-batcher/src/types/batch_queue.rs]: Solved in [b019a36](https://github.com/yetanotherco/aligned_layer/pull/1512/commits/b019a3626f92b0e561fa89d64188b6f185c4f4a3).

File: batcher/aligned-batcher/src/types/batch_queue.rs (hunk 5 above)
Comment (MarcosNicolau) [reply batcher/aligned-batcher/src/types/batch_queue.rs:634]: Solved in [b019a36](https://github.com/yetanotherco/aligned_layer/pull/1512/commits/b019a3626f92b0e561fa89d64188b6f185c4f4a3).

**Review by JuArce — APPROVED** [review]
