### PR TITLE
hotfix(explorer): Fix the proof price average

### LINKED ISSUE #1714: fix(explorer): avg fee per price should be weighted for amt_of_proofs in batch

### PR DESCRIPTION
**Pull request by JulianVentura**
# Fix the proof price average

## Description

This PR fixes the calculation of the proof price average.

## Type of change

Please delete options that are not relevant.

- [ ] New feature
- [X] Bug fix
- [ ] Optimization
- [ ] Refactor

## Checklist

- [X] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

### CODE REVIEW

**Review by MauroToscano — APPROVED** [review]

**Review by PatStiles — APPROVED** [review]

File: explorer/lib/explorer/models/batches.ex [hunk 1]
```diff
@@ -140,22 +140,23 @@ defmodule Batches do
...
-  def get_avg_fee_per_proof() do
+  def get_avg_fee_per_proof(time_range_minutes \\ nil) do
+    threshold_datetime = threshold_datetime_from_minutes_range(time_range_minutes)
+
     query =
       from(b in Batches,
-        where: b.is_verified == true,
-        select: avg(b.fee_per_proof)
+        where: b.is_verified == true and b.submission_timestamp > ^threshold_datetime,
+        select: {b.fee_per_proof, b.amount_of_proofs}
```
Comment (JuArce) [inline explorer/lib/explorer/models/batches.ex]: If the parameter is nil, it will bring all the proof in memory

**Review by JuArce — CHANGES_REQUESTED** [review]

**Review by JuArce — APPROVED** [review]

**Review by uri-99 — APPROVED** [review]
