### PR TITLE
fix (operator): retry connection to aggregator when disconnected

### LINKED ISSUE #94: fix (operator): retry connection to aggregator when disconnected
When killing aggregator while operator is running, operator never tries to reconnect to aggregator. Its connection is shut down until operator is restarted again.

# To reproduce

In separate terminals
1. `make anvil-start`
2.`make aggregator-start`
3. `make operator-full-registration operator-start`

Then wait for operator to be started correctly & kill and restart aggregator.
Then run:
`make send-plonk-proof`

See error in operator session:
`Received error from aggregator {"err":"connection is shut down"}`

Expected behavior:
Operator should try to reconnect to aggregator when connection is shut down

### PR DESCRIPTION
**Pull request by NicolasRampoldi**
# Description
- Now operator retries to connect to aggregator when the aggregator is shut down.

### CODE REVIEW

**Review by entropidelic — APPROVED** [review]

File: operator/pkg/rpc_client.go [hunk 1]
```diff
@@ -31,10 +38,24 @@ func NewAggregatorRpcClient(aggregatorIpPortAddr string, logger logging.Logger)
...
+				c.logger.Error("Aggregator is shutdown. Reconnecting...")
+				client, err := rpc.DialHTTP("tcp", c.aggregatorIpPortAddr)
+				if err != nil {
+					c.logger.Error("Could not reconnect to aggregator", "err", err)
+					time.Sleep(RetryInterval)
+				} else {
+					c.rpcClient = client
+					c.logger.Info("Reconnected to aggregator")
+				}
+			}
```
Comment (uri-99) [inline operator/pkg/rpc_client.go:58]: Should every error wait the time interval before retrying to send the task?
```suggestion
			} else { 
			     c.logger.Info("Unhandled Error, waiting before retry")
			     time.Sleep(RetryInterval)
			}
```

**Review by uri-99 — APPROVED** [review]
looks good
