### PR TITLE
fix: improve sp1 proof handling

### LINKED ISSUE #2035: fix: improve sp1 proof handling

### PR DESCRIPTION
**Pull request by JuArce**
# Improve SP1 Proof Handling

## Description

Improve sp1 handling

## Type of change

- [x] Bug fix

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change crates/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

### CODE REVIEW

**Review by MarcosNicolau — APPROVED** [review]

File: operator/sp1/sp1.go [hunk 1]
```diff
@@ -29,9 +29,16 @@ func VerifySp1Proof(proofBuffer []byte, elfBuffer []byte) (isVerified bool, err
 	}()
 
 	proofPtr := (*C.uchar)(unsafe.Pointer(&proofBuffer[0]))
+	//publicInputsPtr := (*C.uchar)(unsafe.Pointer(&publicInputsBuffer[0]))
```
Comment (MauroToscano) [inline operator/sp1/sp1.go]: This commented code could be deleted if it's not needed

```suggestion
```

**Review by maximopalopoli — APPROVED** [review]

**Review by MauroToscano — APPROVED** [review]
