### PR TITLE
fix(explorer): handle empty events from batcher payment system

### LINKED ISSUE #886: fix(explorer): handle empty event from batcher payment contract

### PR DESCRIPTION
**Pull request by glpecile**
# Changes

* update text to say fee
* add case when empty array from events and add log
* do not display batch fee that returned empty from logs

### CODE REVIEW

File: explorer/lib/explorer/contract_managers/batcher_payment_service_manager.ex [hunk 1]
```diff
@@ -48,6 +48,10 @@ defmodule BatcherPaymentServiceManager do
     )
     |> Ethers.get_logs(fromBlock: @first_block)
     |> case do
+      {:ok, []} ->
+        Logger.error("No events found for merkle root: #{merkle_root}")
```
Comment (uri-99) [inline explorer/lib/explorer/contract_managers/batcher_payment_service_manager.ex]:
```suggestion
        Logger.error("No task_created events found on BatcherPayments for merkle root: #{merkle_root}")
```

**Review by uri-99 — CHANGES_REQUESTED** [review]

**Review by uri-99 — APPROVED** [review]

File: explorer/lib/explorer/contract_managers/batcher_payment_service_manager.ex [hunk 2]
```diff
@@ -48,20 +48,24 @@ defmodule BatcherPaymentServiceManager do
...
       {:error, reason} ->
-        Logger.error("Error getting gas per proof: #{inspect(reason)}")
-        raise("Error getting gas per proof")
+        Logger.error("Error getting fee per proof: #{inspect(reason)}.")
+        raise("Error getting fee per proof events.")
 
       other ->
-        Logger.error("Unexpected response: #{inspect(other)}")
-        raise("Unexpected response")
+        Logger.error("Unexpected response onfee per proof events: #{inspect(other)}")
```
Comment (glpecile) [inline explorer/lib/explorer/contract_managers/batcher_payment_service_manager.ex]:
```suggestion
        Logger.error("Unexpected response on fee per proof events: #{inspect(other)}")
```

File: explorer/lib/explorer/models/batches.ex [hunk 3]
```diff
@@ -34,7 +34,7 @@ defmodule Batches do
     |> validate_format(:submission_transaction_hash, ~r/0x[a-fA-F0-9]{64}/)
     |> validate_number(:response_block_number, greater_than: 0)
     |> validate_format(:response_transaction_hash, ~r/0x[a-fA-F0-9]{64}/)
-    |> validate_number(:fee_per_proof, greater_than: 0)
+    |> validate_number(:fee_per_proof, greater_than: -1)
```
Comment (entropidelic) [inline explorer/lib/explorer/models/batches.ex]: smol nit, but I think it makes more sense
```suggestion
    |> validate_number(:fee_per_proof, greater_than_or_equal_to: 0)
```

**Review by entropidelic — APPROVED** [review]
