### PR TITLE
fix (sdk): add sender address to wait for verification function

### LINKED ISSUE #898: fix (sdk): add sender address to wait for verification function
The sdk wait_for_verification needs to have the batcher address to call the service manager contract, since it was added as a parameter on `verifyBatchInclusion`

### PR DESCRIPTION
**Pull request by taturosati**
Add batcher payments service address to the following functions on the sdk:

- submit_multiple_and_wait_verification
- submit_and_wait_verification
- is_proof_verified

This is needed for change on aligned service manager where sender address was added to batch identifier.

> [!WARNING] 
> Needs to be merged before automatic upgrade on Tuesday, then we should release this version of sdk.

### CODE REVIEW

**Review by entropidelic — APPROVED** [review]

File: batcher/aligned-sdk/src/sdk.rs [hunk 1]
```diff
@@ -405,6 +430,8 @@ mod test {
 
     use ethers::signers::LocalWallet;
 
+    const BATCHER_PAYMENT_SERVICE_ADDR: &str = "0x7969c5eD335650692Bc04293B07F5BF2e7A673C0";
```
Comment (JuArce) [inline batcher/aligned-sdk/src/sdk.rs:433]: This values is just used for tests right?

**Review by JuArce — CHANGES_REQUESTED** [review]
Lgtm. Merge after block 2_268_375

**Review by uri-99 — APPROVED** [review]

**Review by JuArce — APPROVED** [review]
