### PR TITLE
fix(explorer): fetch_batch_data_pointer in explorer reads the entire response body without any limitation

### LINKED ISSUE #1016: fix(explorer): `fetch_batch_data_pointer` in `explorer` reads the entire response body without any limitation.
## Overview:
The [`fetch_batch_data_pointer`](https://github.com/yetanotherco/aligned_layer/blob/staging/explorer/lib/explorer_web/live/utils.ex#L182) function in the [`explorer`](explorer/lib/explorer_web/live/utils.ex) is vulnerable to an OOM attack.

The function reads the entire response body without any limitation, which can lead to an OOM attack.

## Detailed Behavior
During the processing of a new batch log, the explorer uses a mutex to prevent multiple indexation of the same batch. It periodically checks for new batch logs and processes them. If a batcher takes more time than the interval between two checks, the explorer will lose the other batch logs since it will provoke an OOM and crash the explorer.

## Mitigation
Set a timeout for the request to prevent an OOM attack.

### PR DESCRIPTION
**Pull request by avilagaston9**
**Motivation**

The function `fetch_batch_data_pointer` in the explorer reads the entire response body without any
limitations, which can lead to an OOM attack.

**Description**

Uses a `max_batch_size` limit when reading request bodies.

**How to Test**

See #1202 

Closes #1016

### CODE REVIEW

**Review by uri-99 — APPROVED** [review]

**Review by uri-99 — CHANGES_REQUESTED** [review]
WIP

File: explorer/lib/explorer_web/live/utils.ex [hunk 1]
```diff
@@ -132,6 +132,7 @@ end
 # Backend utils
 defmodule Utils do
   require Logger
+  @max_batch_size String.to_integer(System.get_env("MAX_BATCH_SIZE") || "268435456")
```
Comment (uri-99) [inline explorer/lib/explorer_web/live/utils.ex]:
```suggestion
  @max_batch_size (case System.fetch_env("MAX_BATCH_SIZE") do
    {:ok, ""} -> 268_435_456 #empty env var
    {:ok, value} -> String.to_integer(value)
    _ -> 268_435_456 # error
  end)
```

File: explorer/lib/explorer_web/live/utils.ex [hunk 2]
```diff
@@ -245,9 +262,17 @@ defmodule Utils do
...
+          batch_content = batch.data_pointer |> Utils.fetch_batch_data_pointer()
+          case batch_content do
+            {:ok, batch_content} ->
+              batch_content
+              |> Utils.calculate_proof_hashes()
+
+            {:error, reason} ->
+              Logger.error("Error fetching batch content: #{inspect(reason)}")
+              # Returning something ensures we avoid attempting to fetch the invalid data again.
+              ["invalid batch"]
```
Comment (uri-99) [inline explorer/lib/explorer_web/live/utils.ex]: This string is converted to hex in frontend, better handle invalids in a cleaner way

**Review by uri-99 — CHANGES_REQUESTED** [review]
It would be best to have another state for the batch.
For this a new ecto migrate is needed, adding an `is_valid` bool to the batches table.
Also the schemas should be updated, and the value should be set to false if the batch is not valid.

Also in the frontend, invalid proofs should be shown a red `invalid` status.

File: explorer/lib/explorer_web/live/utils.ex [hunk 3]
```diff
@@ -167,21 +172,36 @@ defmodule Utils do
...
+    do: {:halt, {:error, {:http_error, status_code}}}
+
+  defp stream_handler({:data, chunk}, {_acc_body, size})
+       when size + byte_size(chunk) > @max_batch_size do
+    {:halt, {:error, {:http, :body_too_large}}}
+  end
+
+  defp stream_handler({:data, chunk}, {acc_body, size}) do
+    new_size = size + byte_size(chunk)
+    {:cont, {acc_body <> chunk, new_size}}
```
Comment (entropidelic) [inline explorer/lib/explorer_web/live/utils.ex]: instead of separating the function in these two cases, I think it is a bit more understandable to condense these in one function and check the condition `size + byte_size(chunk) > @max_batch_size` inside it

Comment (entropidelic) [reply explorer/lib/explorer_web/live/utils.ex]: also, for consistency I think it is better to rename `{acc_body, size}` to `{acc_body, acc_size}`

File: explorer/lib/explorer_web/live/utils.ex [hunk 4]
```diff
@@ -167,21 +172,36 @@ defmodule Utils do
...
     deserialized_batch
     |> Enum.map(fn s3_object ->
       :crypto.hash(:sha3_256, s3_object["proof"])
     end)
   end
 
-  def calculate_proof_hashes({:error, reason}) do
-    Logger.error("Error calculating proof hashes: #{inspect(reason)}")
-    []
+  defp stream_handler({:headers, _headers}, acc), do: {:cont, acc}
```
Comment (entropidelic) [inline explorer/lib/explorer_web/live/utils.ex]: we could add a check here to validate that the content lenght in the request header is not greater than the maximum batch size, like we have in the operator side, in order to avoid downloading unecessary data https://github.com/yetanotherco/aligned_layer/blob/477de1d5801b93507427eb7cb8e3504ac55dc617/operator/pkg/s3.go#L73

**Review by JuArce — COMMENTED** [review]
Same comments as Marian

File: explorer/lib/explorer_web/live/utils.ex (hunk 3 above)
Comment (avilagaston9) [reply explorer/lib/explorer_web/live/utils.ex]: Done!

File: explorer/lib/explorer_web/live/utils.ex (hunk 4 above)
Comment (avilagaston9) [reply explorer/lib/explorer_web/live/utils.ex]: Nice! Added.

File: explorer/lib/explorer_web/live/utils.ex (hunk 2 above)
Comment (avilagaston9) [reply explorer/lib/explorer_web/live/utils.ex]: Changed to `[<<0>>]` to show `0x0` in the frontend for now. I'm solving this in a different PR in case we need to merge this one.

**Review by uri-99 — APPROVED** [review]

**Review by MarcosNicolau — APPROVED** [review]
Tested on macos.

**Review by entropidelic — APPROVED** [review]
