### PR TITLE
fix(operator): reduce polling frecuency and remove newbatchv2 logic

### LINKED ISSUE #2074: fix(operator): reduce polling frecuency and remove newBatchV2 logic

### PR DESCRIPTION
**Pull request by JuArce**
# Reduce polling frecuency and remove newbatchv2 logic

## Description

Closes #2074

## Type of change

- [x] Bug fix
- [x] Optimization
- [x] Refactor

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change crates/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

### CODE REVIEW

File: operator/pkg/operator.go [hunk 1]
```diff
@@ -209,14 +202,8 @@ func (o *Operator) UpdateLastProcessBatch(blockNumber uint32) error {
...
-	errorPair := o.SubscribeToNewTasksV2(subV2ErrorChannel)
-	if errorPair != nil {
-		log.Fatal("Could not subscribe to new tasks")
-	}
-
 	subV3ErrorChannel := make(chan chainio.ErrorPair)
-	errorPair = o.SubscribeToNewTasksV3(subV3ErrorChannel)
+	errorPair := o.SubscribeToNewTasksV3(subV3ErrorChannel)
 	if errorPair != nil {
 		log.Fatal("Could not subscribe to new tasks")
```
Comment (MauroToscano) [inline operator/pkg/operator.go:208]: Is this still errorPair ? There is no pair now, right ?

**Review by MauroToscano — APPROVED** [review]

**Review by MarcosNicolau — APPROVED** [review]
Beatiful.

**Review by MarcosNicolau — APPROVED** [review]
Very beautiful.

**Review by MarcosNicolau — APPROVED** [review]
