### PR TITLE
fix: operator downtime

### LINKED ISSUE #978: fix: getLatestTaskFromEthereum should use filterer
Currently, getLatestTaskFromEthereum in `avs_subscriber.go` , parses an ABI to make a client request of a NewBatch log. It says:
```
The alternative to this is using the FilterNewBatch method from the contract's filterer, but it requires
to iterate over all the logs, which is not efficient and not needed since we only need the latest task.
```

Which is not true, since bindings filterer accepts, in `filteropts, the `fromBlock` and `toBlock` parameters.

This is why, `getLatestTaskFromEthereum` should use the bindings filterer. Using them, errors here appear on compilation and not on runtime (which was an error we had in the operators, where `NewBatch` did not exist)

### PR DESCRIPTION
**Pull request by MarcosNicolau**
**Changes**
This pr adds a way to recover the operator's tasks from downtime. The way it works now is:
1. We store the latest block at which a batch was finished processing.
2. On startup we read the block and query the `avs_reader` for all the tasks that have not been responded to starting from that block minus `100` (this is to account for the case that a higher block number task finished first than a previous one, since batches can be processed in parallel). This is to be improved with an algorithm by @Oppen.
3. We process the batches as per usual.

A new check is also added to not send already responded blocks in the `avs_subscriber` 'get_latest_task` interval. This problem happened at startup specially, it would always run the latest task doesn't matter how old it was.

**Test**

To make sure everything works, we can run the following test: setup

1. Setup a local testnet as usual: `make anvil_start_with_block`, `make aggregator_start`, `make batcher_start_local`
5. Now for the operators, we'll start four different ones:
    - `1`: `make operator_register_and_start`
    - `2`: `make operator_register_and_start CONFIG_FILE=config-files/config-operator-1.yml`
    - `3`: `make operator_register_and_start CONFIG_FILE=config-files/config-operator-2.yml`
    - `4`: `make operator_register_and_start CONFIG_FILE=config-files/config-operator-3.yml`
7. Send some proofs to the batcher to make sure everything is working: `make batcher_send_plonk_bls12_381_burst `
8. Stop operator `2`, `3` and `4`
9. Again send more proofs : `make batcher_send_risc0_burst` (it is better if you send many batches)
10. You should see that aggregator is waiting for more verifications to send the response
11. Start operator `2` and `3` again: 
      - `make operator_start CONFIG_FILE=config-files/config-operator-1.yml`
      - `make operator_start CONFIG_FILE=config-files/config-operator-2.yml`
13. You should see quorum is reached and the aggregator sends the response
14. Start operator `4`: `make operator_start CONFIG_FILE=config-files/config-operator-3.yml`
15. You should see that it doesn't in fact perform the tasks as the batches have already been responded to.

## Deploy 

> [!WARNING]
> This PR adds the following parameter to the operator configuration `last_processed_batch_filepath: '<>'`

Advances on #962
Closes #978

### CODE REVIEW

File: operator/pkg/operator.go [hunk 1]
```diff
@@ -181,6 +238,29 @@ func (o *Operator) Start(ctx context.Context) error {
 	}
 }
 
+// Here we query all the batches that have not yet been verified starting from
+// the latest verified batch by the operator. We also get the prior 5 and check if we need to verify them as well
+// This last thing of getting the last 5 is to make sure we have not missed a batch since they are process in parallel
+// and a higher batch number might have been processed first than the lower one.
+// So getting the last five accounts for that case
```
Comment (Oppen) [inline operator/pkg/operator.go]: I'm not sure the magic 5 solves the issue if they run in parallel. Imagine a given batch, say batch `3` takes longer than the others, then the others threads advance through blocks `4`, `5`, `6`, up to, say, `10`. Then you'll miss `3`, because `10-5=5`.

File: operator/pkg/operator.go [hunk 2]
```diff
@@ -181,6 +238,29 @@ func (o *Operator) Start(ctx context.Context) error {
...
+func (o *Operator) ProcessMissedBatchesWhileOffline(c chan int) {
+	// this means there was no file or no batches have been verified
+	if o.lastProcessedBatch.BlockNumber == 0 {
+		c <- 0
+		return
+	}
```
Comment (Oppen) [inline operator/pkg/operator.go]: I think we should add a log for this. I picture an error condition where:
1. Service died during marshal, and because of that
2. Recovery finds a corrupted file, so
3. We silently don't recover as expected.

File: operator/pkg/operator.go [hunk 3]
```diff
@@ -194,6 +274,7 @@ func (o *Operator) Start(ctx context.Context) error {
 func (o *Operator) handleNewBatchLogV2(newBatchLog *servicemanager.ContractAlignedLayerServiceManagerNewBatchV2) {
 	o.Logger.Infof("Received new batch log V2")
 	err := o.ProcessNewBatchLogV2(newBatchLog)
+	o.UpdateLastProcessBatch(newBatchLog.TaskCreatedBlock)
```
Comment (Oppen) [inline operator/pkg/operator.go]: This should happen only after we finish verifying. Possibly `defer` this.

Comment (Oppen) [reply operator/pkg/operator.go]: Also, the way this is updated looks like a data race. We should probably write a buffered channel instead, so a single goroutine updates the value and writes the file. Possibly as part of the `select` on the main loop.

Comment (MarcosNicolau) [reply operator/pkg/operator.go]: Yeah that's a data race 100%

File: operator/pkg/operator.go (hunk 1 above)
Comment (MarcosNicolau) [reply operator/pkg/operator.go]: Yes... I guess no number can cover this cases 100%. But given that each batch is produced every 12 seconds, It might be too improbable for 5 or 10 new batches to finish before the oldest ones. Although increasing the number might help, maybe we should came up with a better method or maybe it is just unnecessary. We should discuss more.

Comment (MarcosNicolau) [reply operator/pkg/operator.go]: Updated!

File: core/chainio/avs_reader.go [hunk 4]
```diff
@@ -59,6 +70,73 @@ func (r *AvsReader) GetErc20Mock(tokenAddr gethcommon.Address) (*contractERC20Mo
 	return erc20Mock, nil
 }
 
-func (r *AvsReader) IsOperatorRegistered(address gethcommon.Address) (bool, error) {
+func (r *AvsReader) IsOperatorRegistered(address ethcommon.Address) (bool, error) {
 	return r.ChainReader.IsOperatorRegistered(&bind.CallOpts{}, address)
 }
+
+// Returns all the "NewBatchV3" logs that have not been responded starting from the given block number
+func (r *AvsReader) GetNotRespondedTasksFrom(fromBlock uint64) ([]servicemanager.ContractAlignedLayerServiceManagerNewBatchV3, error) {
```
Comment (MarcosNicolau) [inline core/chainio/avs_reader.go:73]: Should we create two functions `GetNotRespondedTasksFromV3` and `GetNotRespondedTasksFromV2` here and choose which one to call based on the operator version?

File: operator/pkg/operator.go [hunk 5]
```diff
@@ -136,6 +149,51 @@ func (o *Operator) SubscribeToNewTasksV3() (chan error, error) {
...
+	if err != nil {
+		return fmt.Errorf("failed to marshal batch: %v", err)
+	}
+
+	err = os.WriteFile(o.lastProcessedBatchLogFile, json, os.ModePerm)
+	if err != nil {
+		return fmt.Errorf("failed to write to file: %v", err)
+	}
+
+	o.Logger.Info("Updated latest block json file")
```
Comment (Oppen) [inline operator/pkg/operator.go]: Consider also printing the block number here.

File: operator/pkg/operator.go [hunk 6]
```diff
@@ -174,13 +235,43 @@ func (o *Operator) Start(ctx context.Context) error {
...
+			go o.handleNewBatchLogV3(newBatchLogV3, batchProcessorChan)
+		case bacthProcessed := <-batchProcessorChan:
+			_ = o.UpdateLastProcessBatch(bacthProcessed)
+
 		}
 	}
 }
 
+// Here we query all the batches that have not yet been verified starting from
+// the latest verified batch by the operator. We also get the prior 5 and check if we need to verify them as well
```
Comment (Oppen) [inline operator/pkg/operator.go]:
```suggestion
// the latest verified batch by the operator. We also get the prior 100 and check if we need to verify them as well
```

File: operator/pkg/operator.go [hunk 7]
```diff
@@ -174,13 +235,43 @@ func (o *Operator) Start(ctx context.Context) error {
 				o.Logger.Fatal("Could not subscribe to new tasks V3")
 			}
 		case newBatchLogV2 := <-o.NewTaskCreatedChanV2:
-			go o.handleNewBatchLogV2(newBatchLogV2)
+			go o.handleNewBatchLogV2(newBatchLogV2, batchProcessorChan)
 		case newBatchLogV3 := <-o.NewTaskCreatedChanV3:
-			go o.handleNewBatchLogV3(newBatchLogV3)
+			go o.handleNewBatchLogV3(newBatchLogV3, batchProcessorChan)
+		case bacthProcessed := <-batchProcessorChan:
+			_ = o.UpdateLastProcessBatch(bacthProcessed)
```
Comment (Oppen) [inline operator/pkg/operator.go]: We should at least log the error, if any.

File: core/chainio/avs_reader.go (hunk 4 above)
Comment (Oppen) [reply core/chainio/avs_reader.go:73]: I'm not sure if two functions are needed, but we should be able to handle both versions, right?

File: operator/pkg/operator.go (hunk 5 above)
Comment (MarcosNicolau) [reply operator/pkg/operator.go]: Updated!

**Review by Oppen — APPROVED** [review]

File: operator/pkg/operator.go [hunk 8]
```diff
@@ -136,6 +149,51 @@ func (o *Operator) SubscribeToNewTasksV3() (chan error, error) {
 	return o.avsSubscriber.SubscribeToNewTasksV3(o.NewTaskCreatedChanV3)
 }
 
+type OperatorLastProcessedBatch struct {
+	BlockNumber uint32 `json:"block_number"`
+}
```
Comment (uri-99) [inline operator/pkg/operator.go]: Is this overhead really necessary and useful?

File: operator/pkg/operator.go [hunk 9]
```diff
@@ -136,6 +149,51 @@ func (o *Operator) SubscribeToNewTasksV3() (chan error, error) {
...
+	if err != nil {
+		return fmt.Errorf("failed to marshal batch: %v", err)
+	}
+
+	err = os.WriteFile(o.lastProcessedBatchLogFile, json, os.ModePerm)
+	if err != nil {
+		return fmt.Errorf("failed to write to file: %v", err)
+	}
+
+	o.Logger.Info("Updated latest block json file, new block: %v", blockNumber)
```
Comment (uri-99) [inline operator/pkg/operator.go]: check how much is this logging, i think it does it on every batch. is it too much?

File: config-files/config-operator-1.yaml [hunk 10]
```diff
@@ -31,6 +31,7 @@ operator:
   enable_metrics: true
   metrics_ip_port_address: localhost:9092
   max_batch_size: 268435456 # 256 MiB
+  last_processed_batch_filepath: "operator-1.json"
```
Comment (uri-99) [inline config-files/config-operator-1.yaml]: this file is being stored in the root of the project, it should be stored somewhere more relevant, such as in config-files.

Comment (uri-99) [reply config-files/config-operator-1.yaml]: Actually, why is this another file? it could be an extra parameter in the already existing `config-operator.yaml`

File: operator/pkg/operator.go [hunk 11]
```diff
@@ -174,13 +235,44 @@ func (o *Operator) Start(ctx context.Context) error {
...
 			}
 		case newBatchLogV2 := <-o.NewTaskCreatedChanV2:
-			go o.handleNewBatchLogV2(newBatchLogV2)
+			go o.handleNewBatchLogV2(newBatchLogV2, batchProcessorChan)
 		case newBatchLogV3 := <-o.NewTaskCreatedChanV3:
-			go o.handleNewBatchLogV3(newBatchLogV3)
+			go o.handleNewBatchLogV3(newBatchLogV3, batchProcessorChan)
+		case bacthProcessed := <-batchProcessorChan:
+			err = o.UpdateLastProcessBatch(bacthProcessed)
+			o.Logger.Errorf("Error while updating last process batch", "err", err)
```
Comment (uri-99) [inline operator/pkg/operator.go]: im getting this error out of the box
image

File: operator/pkg/operator.go [hunk 12]
```diff
@@ -174,13 +235,44 @@ func (o *Operator) Start(ctx context.Context) error {
...
+func (o *Operator) ProcessMissedBatchesWhileOffline(c chan uint32) {
+	// this is the default value
+	// and it means there was no file so no batches have been verified
+	if o.lastProcessedBatch.BlockNumber == 0 {
+		o.Logger.Info("Not continuing with missed batch processing, as operator hasn't verified anything yet...")
+		return
+	}
+
+	o.Logger.Info("Getting missed tasks")
+	logs, err := o.avsReader.GetNotRespondedTasksFrom(uint64(o.lastProcessedBatch.BlockNumber - 100))
```
Comment (uri-99) [inline operator/pkg/operator.go]: magic number `100`. This number should be a better defined constant. Either in the config file, or maybe a bit simpler as a const in this file (similar to near line 63 of this file)

File: operator/pkg/operator.go [hunk 13]
```diff
@@ -174,13 +235,44 @@ func (o *Operator) Start(ctx context.Context) error {
...
+
 		}
 	}
 }
 
+// Here we query all the batches that have not yet been verified starting from
+// the latest verified batch by the operator. We also get the prior 100 and check if we need to verify them as well
+// This last thing of getting the last 100 is to make sure we have not missed a batch since they are process in parallel
+// and a higher batch number might have been processed first than the lower one.
+// So getting the last 100 accounts for such cases
```
Comment (uri-99) [inline operator/pkg/operator.go]:
```suggestion
// Here we query all the batches that have not yet been verified starting from
// the latest verified batch by the operator. We also read from the previous
// 100 blocks, because as batches are processed in parallel, there could be
// unverified batches slightly before the latest verified batch
```

File: operator/pkg/operator.go [hunk 14]
```diff
@@ -154,6 +212,9 @@ func (o *Operator) Start(ctx context.Context) error {
 		metricsErrChan = make(chan error, 1)
 	}
 
+	batchProcessorChan := make(chan uint32)
```
Comment (uri-99) [inline operator/pkg/operator.go]: This channel is to mark a batch as processed, right?
```suggestion
	batchProcessedChan := make(chan uint32)
```

File: operator/pkg/operator.go [hunk 15]
```diff
@@ -174,13 +235,44 @@ func (o *Operator) Start(ctx context.Context) error {
 				o.Logger.Fatal("Could not subscribe to new tasks V3")
 			}
 		case newBatchLogV2 := <-o.NewTaskCreatedChanV2:
-			go o.handleNewBatchLogV2(newBatchLogV2)
+			go o.handleNewBatchLogV2(newBatchLogV2, batchProcessorChan)
 		case newBatchLogV3 := <-o.NewTaskCreatedChanV3:
-			go o.handleNewBatchLogV3(newBatchLogV3)
+			go o.handleNewBatchLogV3(newBatchLogV3, batchProcessorChan)
```
Comment (uri-99) [inline operator/pkg/operator.go]: Instead of passing the `batchProcessedChan` as parameter, it would be best for the relevant functions to call something like `o.registerBatchProcessed(int)` which sends a message to the channel. 
Hint: `type Operator struct {` should probably have a chan for this to work.

File: operator/pkg/operator.go [hunk 16]
```diff
@@ -191,9 +283,16 @@ func (o *Operator) Start(ctx context.Context) error {
 // different events enables the smooth operator upgradeability
 
 // Process of handling batches from V2 events:
-func (o *Operator) handleNewBatchLogV2(newBatchLog *servicemanager.ContractAlignedLayerServiceManagerNewBatchV2) {
+func (o *Operator) handleNewBatchLogV2(newBatchLog *servicemanager.ContractAlignedLayerServiceManagerNewBatchV2, batchProcessedChan chan uint32) {
+	var err error
+	defer func() {
+		if err == nil {
+			batchProcessedChan <- uint32(newBatchLog.Raw.BlockNumber)
```
Comment (uri-99) [inline operator/pkg/operator.go]: Here instead of sending a message to the chan it received as a parameter, it would be best to either call a function that sends the message to the chan, or call a chan stored in the operator struct. I prefer the former to avoid repeting the code that sends a message to a chan.

File: operator/pkg/operator.go [hunk 17]
```diff
@@ -262,9 +361,15 @@ func (o *Operator) ProcessNewBatchLogV2(newBatchLog *servicemanager.ContractAlig
 }
 
 // Process of handling batches from V3 events:
-func (o *Operator) handleNewBatchLogV3(newBatchLog *servicemanager.ContractAlignedLayerServiceManagerNewBatchV3) {
+func (o *Operator) handleNewBatchLogV3(newBatchLog *servicemanager.ContractAlignedLayerServiceManagerNewBatchV3, batchProcessedChan chan uint32) {
+	var err error
+	defer func() {
+		if err == nil {
+			batchProcessedChan <- uint32(newBatchLog.Raw.BlockNumber)
```
Comment (uri-99) [inline operator/pkg/operator.go]: Ditto

File: core/chainio/avs_reader.go [hunk 18]
```diff
@@ -59,6 +70,73 @@ func (r *AvsReader) GetErc20Mock(tokenAddr gethcommon.Address) (*contractERC20Mo
...
+		Topics:    [][]ethcommon.Hash{{newBatchEvent.ID, {}}},
+	}
+
+	logs, err := r.AvsContractBindings.ethClient.FilterLogs(context.Background(), query)
+	if err != nil {
+		logs, err = r.AvsContractBindings.ethClientFallback.FilterLogs(context.Background(), query)
+		if err != nil {
+			return nil, fmt.Errorf("failed to get logs: %w", err)
+		}
+	}
```
Comment (uri-99) [inline core/chainio/avs_reader.go]: FilterNewBatchV3 from go bindings (contracts/bindings/AlignedLayerServiceManager/binding.go) takes care of this. In its FilterOpts you can set the FromBlock (called Start).

All this will be removed when using out go bindings

File: core/chainio/avs_reader.go [hunk 19]
```diff
@@ -59,6 +70,73 @@ func (r *AvsReader) GetErc20Mock(tokenAddr gethcommon.Address) (*contractERC20Mo
...
+
+	var tasks []servicemanager.ContractAlignedLayerServiceManagerNewBatchV3
+
+	for _, logEntry := range logs {
+		var task servicemanager.ContractAlignedLayerServiceManagerNewBatchV3
+
+		err := alignedLayerServiceManagerABI.UnpackIntoInterface(&task, "NewBatchV3", logEntry.Data)
+		if err != nil {
+			return nil, fmt.Errorf("failed to unpack log data: %w", err)
+		}
```
Comment (uri-99) [inline core/chainio/avs_reader.go]: Ditto

File: core/chainio/avs_reader.go [hunk 20]
```diff
@@ -59,6 +70,73 @@ func (r *AvsReader) GetErc20Mock(tokenAddr gethcommon.Address) (*contractERC20Mo
...
+
+		// The second topic is the batch merkle root, as it is an indexed variable in the contract
+		task.BatchMerkleRoot = logEntry.Topics[1]
```
Comment (uri-99) [inline core/chainio/avs_reader.go]: This will also be simpler to read, avoiding random index access

File: core/chainio/avs_subscriber.go [hunk 21]
```diff
@@ -102,7 +103,9 @@ func (s *AvsSubscriber) SubscribeToNewTasksV2(newTaskCreatedChan chan *servicema
 					s.logger.Debug("Failed to get latest task from blockchain", "err", err)
 					continue
 				}
-				s.processNewBatchV2(latestBatch, batchesSet, newBatchMutex, newTaskCreatedChan)
+				if latestBatch != nil {
+					s.processNewBatchV2(latestBatch, batchesSet, newBatchMutex, newTaskCreatedChan)
```
Comment (uri-99) [inline core/chainio/avs_subscriber.go:103]: nice new feat

File: core/chainio/avs_subscriber.go [hunk 22]
```diff
@@ -358,6 +363,19 @@ func (s *AvsSubscriber) getLatestTaskFromEthereumV2() (*servicemanager.ContractA
 	// The second topic is the batch merkle root, as it is an indexed variable in the contract
 	latestTask.BatchMerkleRoot = lastLog.Topics[1]
 
+	// return the task if has not been responded only
```
Comment (uri-99) [inline core/chainio/avs_subscriber.go]: This functionality currently is useful, but the function name does not indicate this.
This functionality should also refactor its name to `getLatestNonRespondedTask` or similar, to indicate it.

File: core/chainio/avs_subscriber.go [hunk 23]
```diff
@@ -422,6 +440,19 @@ func (s *AvsSubscriber) getLatestTaskFromEthereumV3() (*servicemanager.ContractA
...
```
Comment (uri-99) [inline core/chainio/avs_subscriber.go]: Ditto

File: core/chainio/avs_subscriber.go (hunk 22 above)
Comment (uri-99) [reply core/chainio/avs_subscriber.go]: Also, unrelated, I understand you inspired your getTask using the query from this function. But it is wrong and there is an issue about this incorrect implementation: https://github.com/yetanotherco/aligned_layer/issues/978

**Review by uri-99 — CHANGES_REQUESTED** [review]

File: operator/pkg/operator.go (hunk 8 above)
Comment (MarcosNicolau) [reply operator/pkg/operator.go]: Not really, it just makes it easier when declaring new fields if needed in the future and when writing in the file. I'll see if removing it is worthwhile.

File: operator/pkg/operator.go (hunk 11 above)
Comment (MarcosNicolau) [reply operator/pkg/operator.go]: That typically happens when you try to read at startup and no file has been created. If not created, the operator will create the file at the provided path when writing. I'll make sure to create the file on read as well or change the logging for a `warn` and tell the user the reason.

File: config-files/config-operator-1.yaml (hunk 10 above)
Comment (MarcosNicolau) [reply config-files/config-operator-1.yaml]: Personally, I don't think saving the block to the config file is a good idea, we should discuss it.

File: operator/pkg/operator.go (hunk 11 above)
Comment (MarcosNicolau) [reply operator/pkg/operator.go]: nvm, it is because we should check `err != nil`.

File: core/chainio/avs_reader.go (hunk 18 above)
Comment (MarcosNicolau) [reply core/chainio/avs_reader.go]: Updated!

File: operator/pkg/operator.go (hunk 8 above)
Comment (MarcosNicolau) [reply operator/pkg/operator.go]: I think is better to leave it, as we can put the channel here as well!

File: operator/pkg/operator.go [hunk 24]
```diff
@@ -332,6 +440,18 @@ func (o *Operator) ProcessNewBatchLogV3(newBatchLog *servicemanager.ContractAlig
 	return nil
 }
 
+func (o *Operator) afterHandlingBatchV2(log *servicemanager.ContractAlignedLayerServiceManagerNewBatchV2, succeeded bool) {
+	if succeeded {
+		o.lastProcessedBatch.batchProcessedChan <- uint32(log.Raw.BlockNumber)
```
Comment (uri-99) [inline operator/pkg/operator.go:449]: why not simply
```
err = o.UpdateLastProcessBatch(blockNumber)
```

File: operator/pkg/operator.go [hunk 25]
```diff
@@ -332,6 +440,18 @@ func (o *Operator) ProcessNewBatchLogV3(newBatchLog *servicemanager.ContractAlig
...
+	}
+}
+
+func (o *Operator) afterHandlingBatchV3(log *servicemanager.ContractAlignedLayerServiceManagerNewBatchV3, succeeded bool) {
+	if succeeded {
+		o.lastProcessedBatch.batchProcessedChan <- uint32(log.Raw.BlockNumber)
+	}
+}
```
Comment (uri-99) [inline operator/pkg/operator.go:457]: why not simply
```
err = o.UpdateLastProcessBatch(blockNumber)
```

File: operator/pkg/operator.go
Comment (uri-99) [inline operator/pkg/operator.go:1]: `batchProcessedChan` may be unnecessary, why not call the function directly? 
It would save on overhead code, and the handling of an extra chan

File: core/chainio/avs_subscriber.go [hunk 26]
```diff
@@ -317,59 +318,50 @@ func (s *AvsSubscriber) getLatestTaskFromEthereumV2() (*servicemanager.ContractA
...
+		return nil, nil
+	}
 
-	return &latestTask, nil
+	return lastLog, nil
 }
 
 // getLatestTaskFromEthereum queries the blockchain for the latest task using the FilterLogs method.
 // The alternative to this is using the FilterNewBatch method from the contract's filterer, but it requires
 // to iterate over all the logs, which is not efficient and not needed since we only need the latest task.
```
Comment (uri-99) [inline core/chainio/avs_subscriber.go]: Missing function comment change

**Review by uri-99 — CHANGES_REQUESTED** [review]

File: operator/pkg/operator.go
Comment (MarcosNicolau) [reply operator/pkg/operator.go:1]: It is necessary to prevent any race condition while writing to the file as tasks are processed in parallel. Channels assure us that all messages are executed one by one synchronously and not concurrently.

Comment (uri-99) [reply operator/pkg/operator.go:1]: go chans are a good way of [controlling concurrent  accesses](https://stackoverflow.com/questions/29981050/concurrent-writing-to-a-file).

Comment (Oppen) [reply operator/pkg/operator.go:1]: That channel is a synchronization mechanism. Since we have one value and many tasks trying to write to it, we need to put someone "in charge" of it, and let everyone else message that someone.

File: config-files/config-operator-1.yaml
Comment (Oppen) [inline config-files/config-operator-1.yaml:1]: I believe these changes are unrelated to the PR. Maybe just check the old version.

File: config-files/config-operator-2.yaml
Comment (Oppen) [inline config-files/config-operator-2.yaml:1]: Ditto.

File: config-files/config-operator-3.yaml
Comment (Oppen) [inline config-files/config-operator-3.yaml:1]: Ditto.

File: config-files/config-operator.yaml
Comment (Oppen) [inline config-files/config-operator.yaml:1]: Ditto.

File: config-files/config.yaml
Comment (Oppen) [inline config-files/config.yaml:1]: Ditto.

File: operator/pkg/operator.go [hunk 27]
```diff
@@ -177,10 +240,50 @@ func (o *Operator) Start(ctx context.Context) error {
...
+	logs, err := o.avsReader.GetNotRespondedTasksFrom(fromBlock)
+	if err != nil {
+		return
+	}
+	o.Logger.Infof(fmt.Sprintf("Missed tasks retrieved, total tasks to process: %v", len(logs)))
+
+	o.Logger.Infof("Starting to verify missed batches while offline")
+	for _, logEntry := range logs {
+		go o.handleNewBatchLogV3(&logEntry)
+	}
```
Comment (uri-99) [inline operator/pkg/operator.go]: should return if len(logs) == 0
image

**Review by uri-99 — CHANGES_REQUESTED** [review]
final detail and i think its ready to approve

**Comment by uri-99** [comment]
also add the new .json file to .gitignore to avoid having files with random variables being pushed to the repo

File: config-files/config-operator-1.yaml
Comment (MarcosNicolau) [reply config-files/config-operator-1.yaml:1]: It adds a new field for the operator: `last_processed_batch_filepath`. I'll make sure to not push formatting changes along with actual changes next time!

**Review by uri-99 — APPROVED** [review]

File: core/chainio/avs_subscriber.go [hunk 28]
```diff
@@ -165,12 +164,14 @@ func (s *AvsSubscriber) SubscribeToNewTasksV3(newTaskCreatedChan chan *servicema
 			case newBatch := <-internalChannel:
 				s.processNewBatchV3(newBatch, batchesSet, newBatchMutex, newTaskCreatedChan)
 			case <-pollLatestBatchTicker.C:
-				latestBatch, err := s.getLatestTaskFromEthereumV3()
+				latestBatch, err := s.getLatestNotRespondedTaskFromEthereumV3()
```
Comment (Oppen) [inline core/chainio/avs_subscriber.go:167]: Maybe "Pending" is better than "NotResponded".

Comment (uri-99) [reply core/chainio/avs_subscriber.go:167]: +1

**Comment by Oppen** [comment]
OK, seems to work here.
