### PR TITLE
fix(batcher): Update Lambdaworks Merkle Trees + Update merkle leaves length check in batcher

### LINKED ISSUE #970: fix(batcher): Update Empty Batch Condition
PR: #1067 

The empty batch condition within the batcher can be updated from `current_batch_len < 2` to ` current_batch_size == 0`  after the upstream changes to the lambdaworks merkle tree are merged.

ref: https://github.com/yetanotherco/aligned_layer/blob/staging/batcher/aligned-batcher/src/lib.rs#L254

### PR DESCRIPTION
**Pull request by PatStiles**
closes #970 

- Updates the lambdaworks merkle tree dependencies in aligned layer from v0.7.0 -> v0.10.0. 
- Updates the length check in the batcher to allow batches of size 1

## Testing:

Test local testnet as expected and confirm no errors are emitted.

```
make deps
```

```
make install_aligned_compiling
```

```
make anvil_start_with_block_time
```

```
make aggregator_start
```

```
make operator_register_and_start
```

```
make batcher_start_local
```

```
make batcher_send_burst_groth16
```

## Note:
I removed the [padding](https://github.com/yetanotherco/aligned_layer/blob/staging/batcher/aligned-batcher/src/lib.rs#L1087) of the merkle root leaves  as specified in #979 . However, this caused the Tx to revert in the [BatcherPaymentService](https://github.com/yetanotherco/aligned_layer/blob/staging/contracts/src/core/BatcherPaymentService.sol#L271) contract with InvalidMerkleRoot error (after removing the leaves [power of two check](https://github.com/yetanotherco/aligned_layer/blob/staging/contracts/src/core/BatcherPaymentService.sol#L128)). Since the merkle tree verification was sourced from eigen https://github.com/code-423n4/2023-04-eigenlayer/blob/main/src/contracts/libraries/Merkle.sol#L129 my intuition is its failing due an invariant the leaves are a power of 2 therefore we need to preserve padding the leaves to a power of two. Removing the padding will be done in a separate pr.

### CODE REVIEW

File: batcher/aligned-batcher/src/lib.rs [hunk 1]
```diff
@@ -804,7 +804,7 @@ impl Batcher {
 
         // FIXME(marian): This condition should be changed to current_batch_size == 0
         // once the bug in Lambdaworks merkle tree is fixed.
-        if current_batch_len < 2 {
+        if current_batch_len == 0 {
             info!("Current batch is empty or length 1. Waiting for more proofs...");
```
Comment (uri-99) [inline batcher/aligned-batcher/src/lib.rs]:
```suggestion
            info!("Current batch is empty. Waiting for more proofs...");
```

File: batcher/aligned-batcher/src/lib.rs [hunk 2]
```diff
@@ -1083,7 +1090,6 @@ impl Batcher {
         signatures: Vec<SignatureData>,
         fee_params: CreateNewTaskFeeParams,
     ) -> Result<TransactionReceipt, BatcherError> {
-        // pad leaves to next power of 2
         let padded_leaves = Self::pad_leaves(leaves);
```
Comment (uri-99) [inline batcher/aligned-batcher/src/lib.rs]: Removed comment but still padding the leaves.

The idea is to remove the padding? If the padding is removed, the contract should have a change as well

**Review by uri-99 — CHANGES_REQUESTED** [review]

File: batcher/aligned-batcher/src/lib.rs (hunk 2 above)
Comment (PatStiles) [reply batcher/aligned-batcher/src/lib.rs]: Addressed! Removing the padding lead to Tx reversion in the BatcherPaymentService due to an InvalidMerkleRoot. The comment above goes into more detail.

File: batcher/aligned-batcher/src/lib.rs (hunk 1 above)
Comment (PatStiles) [reply batcher/aligned-batcher/src/lib.rs]: Addressed!

File: operator/merkle_tree/lib/src/lib.rs [hunk 3]
```diff
@@ -86,10 +89,7 @@ mod tests {
         merkle_root_file.read_to_end(&mut root_vec).unwrap();
 
         let mut merkle_root = [0; 32];
-        merkle_root.copy_from_slice(
-            &hex::decode(&root_vec)
-                .unwrap(),
-        );
+        merkle_root.copy_from_slice(&hex::decode(&root_vec).unwrap());
```
Comment (entropidelic) [inline operator/merkle_tree/lib/src/lib.rs:90]: let's not unwrap, return `false`

File: operator/merkle_tree/lib/src/lib.rs [hunk 4]
```diff
@@ -44,7 +44,13 @@ pub extern "C" fn verify_merkle_tree_batch_ffi(
...
 
     let computed_batch_merkle_tree: MerkleTree<VerificationCommitmentBatch> =
-        MerkleTree::build(&batch_data_comm);
+        match MerkleTree::build(&batch_data_comm) {
+            Some(computed_batch_merkle_tree) => computed_batch_merkle_tree,
+            None => {
+                error!("Failed to build merkle tree, batch data commitment is empty");
+                return false;
+            }
+        };
```
Comment (entropidelic) [inline operator/merkle_tree/lib/src/lib.rs]:
```suggestion
        let Ok(computed_batch_merkle_tree) = MerkleTree::build(&batch_data_comm) else {
             error!("Failed to build merkle tree, batch data commitment is empty");
             return false;
            }
        };
```

File: batcher/aligned-batcher/src/lib.rs [hunk 5]
```diff
@@ -806,8 +806,8 @@ impl Batcher {
 
         // FIXME(marian): This condition should be changed to current_batch_size == 0
         // once the bug in Lambdaworks merkle tree is fixed.
-        if current_batch_len < 2 {
-            info!("Current batch is empty or length 1. Waiting for more proofs...");
+        if current_batch_len == 0 {
+            info!("Current batch is empty. Waiting for more proofs...");
             return None;
         }
```
Comment (entropidelic) [inline batcher/aligned-batcher/src/lib.rs]: The FIXME should be removed if it solved. Also, are we using the `current_batch_len` variable anywhere else? If not, then we can remove it and change the condition to
```rust
if batch_state.batch_queue.is_empty()
```

File: operator/merkle_tree/lib/src/lib.rs [hunk 6]
```diff
@@ -66,10 +72,7 @@ mod tests {
         merkle_root_file.read_to_end(&mut root_vec).unwrap();
 
         let mut merkle_root = [0; 32];
-        merkle_root.copy_from_slice(
-            &hex::decode(&root_vec)
-                .unwrap(),
-        );
+        merkle_root.copy_from_slice(&hex::decode(&root_vec).unwrap());
```
Comment (entropidelic) [inline operator/merkle_tree/lib/src/lib.rs:73]: let's not unwrap, return false

File: operator/merkle_tree/lib/src/lib.rs (hunk 4 above)
Comment (PatStiles) [reply operator/merkle_tree/lib/src/lib.rs]: Removed match

File: batcher/aligned-batcher/src/lib.rs (hunk 5 above)
Comment (PatStiles) [reply batcher/aligned-batcher/src/lib.rs]: Comment removed and length check changed

File: operator/merkle_tree/lib/src/lib.rs (hunk 6 above)
Comment (PatStiles) [reply operator/merkle_tree/lib/src/lib.rs:73]: These are in the test and were highlighted after running cargo fmt

File: batcher/aligned-batcher/src/lib.rs [hunk 7]
```diff
@@ -888,7 +885,14 @@ impl Batcher {
...
         let batch_merkle_tree: MerkleTree<VerificationCommitmentBatch> =
-            MerkleTree::build(&batch_data_comm);
+            match MerkleTree::build(&batch_data_comm) {
+                Some(batch_merkle_tree) => batch_merkle_tree,
+                None => {
+                    return Err(BatcherError::TaskCreationError(
+                        "Failed to Build Merkle Tree: Empty Batch".to_string(),
+                    ))
+                }
+            };
```
Comment (Oppen) [inline batcher/aligned-batcher/src/lib.rs]: Nit: this could be more brief by using `ok_or_else`:
```rust
        let batch_merkle_tree: MerkleTree<VerificationCommitmentBatch> =
            MerkleTree::build(&batch_data_comm)
                .ok_or_else(|| Error::TaskCreationError("Failed to Build Merkle Tree: Empty Batch".to_string()))?;
```

File: operator/merkle_tree/lib/src/lib.rs (hunk 3 above)
Comment (PatStiles) [reply operator/merkle_tree/lib/src/lib.rs:90]: The unwrap is present in a unit test.

File: batcher/aligned-batcher/src/lib.rs (hunk 7 above)
Comment (PatStiles) [reply batcher/aligned-batcher/src/lib.rs]: Thanks @Oppen

File: operator/merkle_tree/lib/src/lib.rs (hunk 6 above)
Comment (entropidelic) [reply operator/merkle_tree/lib/src/lib.rs:73]: my bad, sorry

File: operator/merkle_tree/lib/src/lib.rs (hunk 3 above)
Comment (entropidelic) [reply operator/merkle_tree/lib/src/lib.rs:90]: my bad!

**Review by Oppen — APPROVED** [review]

**Review by entropidelic — CHANGES_REQUESTED** [review]
When submitting a batch with only one proof, I am getting
```
Transaction reverted "0x9f13b65cfc222438ea0a6d0738343dfbd7ebd0aaf7a0cbfe1ef69f905eb2bbb6b3dfc6035c58ee0f5eb4cd6f6d30536add1a16cddd8fef8f334968b221c8d45eaf604219"
```

Which corresponds to the `InvalidMerkleRoot` error of the `BatcherPaymentSercvice.sol` contract

**Review by uri-99 — CHANGES_REQUESTED** [review]
Blocking PR until lambdaworks is fixed to allow merkle trees of size 1

**Comment by uri-99** [comment]
Seems to be working fine when pointed to latest commit of LambdaWorks. Waiting to see if a release will be done or if we should point to the latest commit `efd46f0b0aea3aa95d94bba7de86cb96611b40d3`
(probably the former)

**Review by uri-99 — APPROVED** [review]

**Review by MarcosNicolau — APPROVED** [review]
Code looks good, everything worked fine on my machine!

**Review by uri-99 — APPROVED** [review]
still works

**Comment by Oppen** [comment]
> Seems to be working fine when pointed to latest commit of LambdaWorks. Waiting to see if a release will be done or if we should point to the latest commit `efd46f0b0aea3aa95d94bba7de86cb96611b40d3` (probably the former)

I can make a release if we need one. I'll talk with @diegokingston and @MauroToscano.

**Review by entropidelic — APPROVED** [review]
