### PR TITLE
fix(explorer): add real time updates

### LINKED ISSUE #249: fix(explorer): prevent need of refresh to show updated aggregated data
As it is now using live view, it should be able to show the most updated data without the need to refresh the site.

### PR DESCRIPTION
**Pull request by glpecile**
Add pubsub integration hooked to periodically for live updates.

https://github.com/yetanotherco/aligned_layer/assets/58370608/1e78fce2-e520-4f1c-8626-6d2ce9b438f6

https://github.com/yetanotherco/aligned_layer/assets/58370608/aa131073-c792-4e94-bf18-e1b3886949dd

https://github.com/yetanotherco/aligned_layer/assets/58370608/a25e445d-7fcd-4958-ba70-45a886b35bfd

### CODE REVIEW

File: explorer/lib/explorer/periodically.ex [hunk 1]
```diff
@@ -44,6 +45,9 @@ defmodule Explorer.Periodically do
     rescue
       error -> IO.puts("An error occurred during batch processing:\n#{inspect(error)}")
     end
+    PubSub.broadcast(Explorer.PubSub, "update_home", %{})
+    PubSub.broadcast(Explorer.PubSub, "update_batch", %{})
+    PubSub.broadcast(Explorer.PubSub, "update_batches", %{})
```
Comment (ElFantasma) [inline explorer/lib/explorer/periodically.ex]: I don't think we need different topics, as we can publish a single event notifying the same thing: There has been a data update. Subscribers can choose to listen this topic or not.

**Review by ElFantasma — APPROVED** [review]
LGTM

**Review by MauroToscano — APPROVED** [review]

**Review by uri-99 — APPROVED** [review]
