### PR TITLE
fix(ci): run build and test in the same step to avoid recompilation

### LINKED ISSUE #2229: fix(ci): run build and test in the same step to avoid recompilation

### PR DESCRIPTION
**Pull request by JuArce**
# fix(ci): run build and test in the same step to avoid recompilation

## Description

Run build and tests in the same job

## Type of change

- [x] Optimization

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change crates/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

### CODE REVIEW

File: aggregation_mode/proof_aggregator/src/lib.rs [hunk 1]
```diff
@@ -1,2 +1,34 @@
...
+
+use std::env;
+use backend::{config::Config, ProofAggregator};
+use tracing_subscriber::{EnvFilter, FmtSubscriber};
+
+fn read_config_filepath_from_args() -> String {
+    let args: Vec<String> = env::args().collect();
+    if args.len() < 2 {
+        panic!(
+            "You mus provide a config file. Usage: {} <config-file-path>",
```
Comment (maximopalopoli) [inline aggregation_mode/proof_aggregator/src/lib.rs]:
```suggestion
            "You must provide a config file. Usage: {} <config-file-path>",
```

**Review by maximopalopoli — APPROVED** [review]

**Review by MarcosNicolau — APPROVED** [review]
