### PR TITLE
fix: avs subscriber error not being handled correctly

### LINKED ISSUE #625: bug: avs subscriber error not being handled correctly
```
func (s *AvsSubscriber) SubscribeToNewTasks(newTaskCreatedChan chan *servicemanager.ContractAlignedLayerServiceManagerNewBatch) event.Subscription {
	sub, err := s.AvsContractBindings.ServiceManager.WatchNewBatch(
		&bind.WatchOpts{}, newTaskCreatedChan, nil,
	)
	if err != nil {
		s.logger.Error("Failed to subscribe to new AlignedLayer tasks", "err", err)
	}
	s.logger.Infof("Subscribed to new AlignedLayer tasks")
	return sub
}
```

When the subscription can't be established, an error is logged but the function continues and returns nil. This ends up crashing the operator or the aggregator.
We would need to retry the connection a few times and ultimately make the operator shut down gracefully

### PR DESCRIPTION
**Pull request by taturosati**
Added retires on subscribe.

Aggregator still crashes because of eigen sdk in memory subscription to pub keys.

# To test

First test normal flow, then try to kill anvil and operator should stay online and retrying (aggregator will still crash as mentioned above). Restart anvil and operator should resubscribe.

### CODE REVIEW

File: core/chainio/avs_subscriber.go [hunk 1]
```diff
@@ -42,15 +50,22 @@ func NewAvsSubscriberFromConfig(baseConfig *config.BaseConfig) (*AvsSubscriber,
...
-	)
-	if err != nil {
-		s.logger.Error("Failed to subscribe to new AlignedLayer tasks", "err", err)
+func (s *AvsSubscriber) SubscribeToNewTasks(newTaskCreatedChan chan *servicemanager.ContractAlignedLayerServiceManagerNewBatch) (event.Subscription, error) {
+	for i := 0; i < MaxRetries; i++ {
+		sub, err := s.AvsContractBindings.ServiceManager.WatchNewBatch(
+			&bind.WatchOpts{}, newTaskCreatedChan, nil,
+		)
+		if err != nil {
+			s.logger.Info("Failed to subscribe to new AlignedLayer tasks", "err", err)
```
Comment (entropidelic) [inline core/chainio/avs_subscriber.go]: lets make it a warn instead of info

**Review by entropidelic — APPROVED** [review]

**Review by NicolasRampoldi — APPROVED** [review]
