### PR TITLE
fix: minor issues on scripts

### LINKED ISSUE #545: fix: minor issues on scripts

### PR DESCRIPTION
**Pull request by JuArce**
# Changes
- Drop lock in batcher to avoid deadlock (This is a hotfix until we merge https://github.com/yetanotherco/aligned_layer/pull/365)
- Fix private key check in batcher/aligned/generate_proof_and_send.sh
- Load env variables in batcher/aligned/send_burst_tasks.sh

All these are changes I have to made on last deploy to keep all working. It would be nice to merge so I don't have merge conflicts every time in the servers

### CODE REVIEW

File: batcher/aligned-batcher/src/lib.rs [hunk 1]
```diff
@@ -384,10 +384,13 @@ impl Batcher {
...
-            self.submit_batch(&batch_bytes, &batch_merkle_tree.root, submitter_addresses)
-                .await;
             // update last uploaded batch block
             *last_uploaded_batch_block = block_number;
+            // This is a hotfix until we merge https://github.com/yetanotherco/aligned_layer/pull/365
+            drop(last_uploaded_batch_block);
+            info!("Batch Finalizer: Last uploaded batch block updated to: {}. Lock unlocked", block_number);
+            self.submit_batch(&batch_bytes, &batch_merkle_tree.root, submitter_addresses)
+                .await;
         }
```
Comment (taturosati) [inline batcher/aligned-batcher/src/lib.rs]: it does not make sense to call drop manually, self.submit_batch should be outside {}

File: alerts/process_errors_alerts.sh
Comment (srosati) [inline alerts/process_errors_alerts.sh:1]: empty file

**Review by taturosati — APPROVED** [review]

**Review by entropidelic — APPROVED** [review]
