### PR TITLE
fix(operator): manage subscription to events without panic

### LINKED ISSUE #1728: hotfix(operator): manage subscription to events without panic

### PR DESCRIPTION
**Pull request by JuArce**
# Manage Operator's event subscription

## Description

Previously, the Operator panicked if one connection (either main or fallback) failed.

The previous solution to this (#1692) was to iterate infinitely over both connections, this had the "silent failure" problem, as an operator could fail and retry forever without notice to its owner.

Now if one connection fails, the Operator will use the other one, while continiously trying to reconnect to the failed one; and if *both* connections fail, and the retryables are consumed, the Operator will exit, logging the errors of each connection RPC, so the owner/manager of the Operator server can fix it accordingly.

This PR also added the usage of fallback when operator calls `DisableVerifiers`

## To test
1. Start Ethereum Package:
```shell
make ethereum_package_start
```
2. Start verification layer components:
```shell
make aggregator_start_ethereum_package ENVIRONMENT=devnet
make batcher_start_ethereum_package
make operator_register_and_start_ethereum_package ENVIRONMENT=devnet
```
3. Stop and Start the containers ethereum package started for `reth-2` and `reth-3`. `reth-3` is set as the fallback of the operator and `reth-2` as the main node:
```shell
docker stop <NODE_ID>
docker start <NODE_ID>
```

- Verify the Operator behaves as described, and while submitting proofs take down 1 connection, take down the other connection, take down both connections.

## Type of change

Please delete options that are not relevant.

- [x] New feature
- [x] Bug fix
- [ ] Optimization
- [ ] Refactor

## Checklist

- [ ] “Hotfix” to `testnet`, everything else to `staging`
- [ ] Linked to Github Issue
- [ ] This change depends on code or research by an external entity
  - [ ] Acknowledgements were updated to give credit
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run
- [ ] Has a known issue
  - [Link to the open issue addressing it]() 
- [ ] If your PR changes the Operator compatibility (Ex: Upgrade prover versions)
  - [ ] This PR adds compatibility for operator for both versions and do not change batcher/docs/examples
  - [ ] This PR updates batcher and docs/examples to the newer version. This requires the operator are already updated to be compatible

### CODE REVIEW

File: core/chainio/avs_subscriber.go [hunk 1]
```diff
@@ -109,49 +117,61 @@ func (s *AvsSubscriber) SubscribeToNewTasksV2(newTaskCreatedChan chan *servicema
...
+		var auxSub, auxSubFallback event.Subscription
+		for errMain == nil || errFallback == nil { //while one is active
 			select {
 			case err := <-sub.Err():
 				s.logger.Warn("Error in new task subscription", "err", err)
-				sub.Unsubscribe()
-				sub, err = SubscribeToNewTasksV2Retryable(&bind.WatchOpts{}, s.AvsContractBindings.ServiceManager, internalChannel, nil, retry.NetworkRetryParams())
-				if err != nil {
-					errorChannel <- err
+				s.logger.Info("failed states:", "errMain", errMain, "errFallback", errFallback)
```
Comment (JuArce) [inline core/chainio/avs_subscriber.go]: Why are we logging this info after a warn?

File: core/chainio/avs_subscriber.go [hunk 2]
```diff
@@ -109,49 +117,61 @@ func (s *AvsSubscriber) SubscribeToNewTasksV2(newTaskCreatedChan chan *servicema
...
+
+				auxSub, errMain = SubscribeToNewTasksV2Retryable(&bind.WatchOpts{}, s.AvsContractBindings.ServiceManager, internalChannel, nil, retry.NetworkRetryParams())
+				if errMain == nil {
+					//sub.Unsubscribe()
+					sub = auxSub // update the subscription only if it was successful
+					s.logger.Info("Resubscribed to fallback new task subscription")
 				}
 			case err := <-subFallback.Err():
+				s.logger.Info("failed states:", "errMain", errMain, "errFallback", errFallback)
```
Comment (JuArce) [inline core/chainio/avs_subscriber.go]: Why are we logging this info after a warn?

**Review by uri-99 — APPROVED** [review]
biased self-approve

File: aggregator/pkg/subscriber.go [hunk 3]
```diff
@@ -1,18 +1,20 @@
 package pkg
 
-func (agg *Aggregator) SubscribeToNewTasks() error {
-	err := agg.subscribeToNewTasks()
-	if err != nil {
-		return err
+import "github.com/yetanotherco/aligned_layer/core/chainio"
+
+func (agg *Aggregator) SubscribeToNewTasks() *chainio.ErrorPair {
+	errorPairPtr := agg.subscribeToNewTasks()
```
Comment (JuArce) [inline aggregator/pkg/subscriber.go]: I'd rename it to just `errorPair`

File: core/chainio/avs_subscriber.go [hunk 4]
```diff
@@ -109,49 +117,61 @@ func (s *AvsSubscriber) SubscribeToNewTasksV2(newTaskCreatedChan chan *servicema
 
 	// Handle errors and resubscribe
 	go func() {
-		for {
+		var errMain, errFallback error
+		var auxSub, auxSubFallback event.Subscription
+		for errMain == nil || errFallback == nil { //while one is active
 			select {
 			case err := <-sub.Err():
 				s.logger.Warn("Error in new task subscription", "err", err)
```
Comment (JuArce) [inline core/chainio/avs_subscriber.go]:
```suggestion
				s.logger.Warn("Error in main new task subscription", "err", err)
```

**Review by JuArce — COMMENTED** [review]
The same comments apply for V3

**Review by MauroToscano — APPROVED** [review]

File: core/chainio/avs_subscriber.go [hunk 5]
```diff
@@ -109,49 +117,57 @@ func (s *AvsSubscriber) SubscribeToNewTasksV2(newTaskCreatedChan chan *servicema
...
+	s.logger.Info("Starting subscription to new AlignedLayer V3 tasks")
 	// Subscribe to new tasks
-	sub, err := SubscribeToNewTasksV3Retryable(&bind.WatchOpts{}, s.AvsContractBindings.ServiceManager, internalChannel, nil, retry.NetworkRetryParams())
-	if err != nil {
-		s.logger.Error("Primary failed to subscribe to new AlignedLayer V3 tasks after %d retries", MaxRetries, "err", err)
-		return nil, err
+	sub, errMain := SubscribeToNewTasksV3Retryable(&bind.WatchOpts{}, s.AvsContractBindings.ServiceManager, internalChannel, nil, retry.NetworkRetryParams())
+	if errMain != nil {
+		s.logger.Error(fmt.Sprintf("Fallback failed to subscribe to new AlignedLayer V3 tasks after %d retries", MaxRetries), "err", fmt.Sprintf("%v", errMain))
+		//return err
```
Comment (MarcosNicolau) [inline core/chainio/avs_subscriber.go]:
```suggestion

```

File: core/chainio/avs_subscriber.go [hunk 6]
```diff
@@ -109,49 +117,57 @@ func (s *AvsSubscriber) SubscribeToNewTasksV2(newTaskCreatedChan chan *servicema
...
-				sub.Unsubscribe()
-				sub, err = SubscribeToNewTasksV2Retryable(&bind.WatchOpts{}, s.AvsContractBindings.ServiceManager, internalChannel, nil, retry.NetworkRetryParams())
-				if err != nil {
-					errorChannel <- err
+				s.logger.Warn("Error in new task subscription of main connection", "err", err)
+
+				auxSub, errMain = SubscribeToNewTasksV2Retryable(&bind.WatchOpts{}, s.AvsContractBindings.ServiceManager, internalChannel, nil, retry.NetworkRetryParams())
+				if errMain == nil {
+					sub = auxSub // update the subscription only if it was successful
+					s.logger.Info("Resubscribed to fallback new task subscription")
```
Comment (MarcosNicolau) [inline core/chainio/avs_subscriber.go]:
```suggestion
					s.logger.Info("Main connection resubscribed to new task subscription")
```

**Review by MarcosNicolau — APPROVED** [review]
Worked for me. I've updated the `how-to-test` section in the pr description to use `ethereum-package`. Not related to this pr I noticed that when deactivating the fallback of the Batcher, the Batcher stops listening to blocks, thus not creating new batches.
