### PR TITLE
fix: spawn blocking for verification

### LINKED ISSUE #696: fix: blocking in verify
Use Tokio spawn_blocking for cpu intense verification

### PR DESCRIPTION
**Pull request by taturosati**
- Add spawn_blocking around zk_utils::verify 
- Remove lazy_static and replace with std::sync::OnceLock

# To test

Start everything normally

have one terminal running `make batcher_send_burst_groth16` with a .env file at batcher/aligned with the following content:

```
PRIVATE_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
```

Make sure to fund that key by running 
```
cast send 0x7969c5eD335650692Bc04293B07F5BF2e7A673C0 --interactive --value 1ether
```

Then send sp1 task with:

```
make batcher_send_sp1_task
```

Everything should work fine (this is the flow that failed in stage)

### CODE REVIEW

File: batcher/aligned-batcher/src/lib.rs [hunk 1]
```diff
@@ -220,7 +220,20 @@ impl Batcher {
...
+                let ws_conn_sink = outgoing.clone();
+                let batcher = self.clone();
+
+                tokio::spawn(async move {
+                    if let Err(e) = batcher.handle_message(msg, ws_conn_sink).await {
+                        error!("Error when handling message: {:?}", e);
+                    }
+                })
+                .await
+                .unwrap();
```
Comment (NicolasRampoldi) [inline batcher/aligned-batcher/src/lib.rs]: Maybe we can handle the error instead of using unwrap

**Review by entropidelic — APPROVED** [review]

**Review by NicolasRampoldi — APPROVED** [review]
