### PR TITLE
fix (aggregator): improve stability

### LINKED ISSUE #319: ( Batcher ) Bug list on Aggregator
<details>
<summary>bls "not initialized or already completed"
</summary>
</details>

<details>
<summary> websocket: closed 1006  </summary>
aligned-main aligned-aggregator[2110465]: {'level':'error','ts':1717623665.8004365,'caller':'pkg/subscriber.go:35','msg':'Error in subscription','err':'websocket: close 1006 (abnormal closure): unexpected EOF','stacktrace':'[github.com/yetanotherco/aligned_layer/aggregator/internal/pkg.(*Aggregator).subscribeToNewTasksnt/home/ubuntu/repos/aligned_layer/aggregator/internal/pkg/subscriber.go:35ngithub.com/yetanotherco/aligned_layer/aggregator/internal/pkg.(*Aggregator).SubscribeToNewTasksnt/home/ubuntu/repos/aligned_layer/aggregator/internal/pkg/subscriber.go:20nmain.aggregatorMain.func1nt/home/ubuntu/repos/aligned_layer/aggregator/cmd/main.go:54](http://github.com/yetanotherco/aligned_layer/aggregator/internal/pkg.(*Aggregator).subscribeToNewTasksnt/home/ubuntu/repos/aligned_layer/aggregator/internal/pkg/subscriber.go:35ngithub.com/yetanotherco/aligned_layer/aggregator/internal/pkg.(*Aggregator).SubscribeToNewTasksnt/home/ubuntu/repos/aligned_layer/aggregator/internal/pkg/subscriber.go:20nmain.aggregatorMain.func1nt/home/ubuntu/repos/aligned_layer/aggregator/cmd/main.go:54)'}
</details>

<details>
<summary> transaction receipt not found for txHash  </summary>
Jun 05 21:39:08 aligned-main aligned-aggregator[2110465]: {'level':'error','ts':1717623548.2852757,'caller':'pkg/aggregator.go:204','msg':'Aggregator failed to respond to task','err':'transaction receipt not found for txHash: 0x338850471a1ba3d0b78b4d04a975252b713eb968ae28c0c9ed44fc4a20a38c7e','stacktrace':'[github.com/yetanotherco/aligned_layer/aggregator/internal/pkg.(*Aggregator).sendAggregatedResponseToContractnt/home/ubuntu/repos/aligned_layer/aggregator/internal/pkg/aggregator.go:204ngithub.com/yetanotherco/aligned_layer/aggregator/internal/pkg.(*Aggregator).Startnt/home/ubuntu/repos/aligned_layer/aggregator/internal/pkg/aggregator.go:162nmain.aggregatorMainnt/home/ubuntu/repos/aligned_layer/aggregator/cmd/main.go:60ngithub.com/urfave/cli/v2.(*Command).Runnt/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279ngithub.com/urfave/cli/v2.(*App).RunContextnt/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337ngithub.com/urfave/cli/v2.(*App).Runnt/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311nmain.mainnt/home/ubuntu/repos/aligned_layer/aggregator/cmd/main.go:35nruntime.mainnt/usr/local/go/src/runtime/proc.go:271](http://github.com/yetanotherco/aligned_layer/aggregator/internal/pkg.(*Aggregator).sendAggregatedResponseToContractnt/home/ubuntu/repos/aligned_layer/aggregator/internal/pkg/aggregator.go:204ngithub.com/yetanotherco/aligned_layer/aggregator/internal/pkg.(*Aggregator).Startnt/home/ubuntu/repos/aligned_layer/aggregator/internal/pkg/aggregator.go:162nmain.aggregatorMainnt/home/ubuntu/repos/aligned_layer/aggregator/cmd/main.go:60ngithub.com/urfave/cli/v2.(*Command).Runnt/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279ngithub.com/urfave/cli/v2.(*App).RunContextnt/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337ngithub.com/urfave/cli/v2.(*App).Runnt/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311nmain.mainnt/home/ubuntu/repos/aligned_layer/aggregator/cmd/main.go:35nruntime.mainnt/usr/local/go/src/runtime/proc.go:271)'}
</details>

### PR DESCRIPTION
**Pull request by taturosati**
In this PR we fixed multiple issues to increase stability:

- We have changed the aggregator to use only one Mutex for all 3 data types that are related to the state of the local indexes and the Merkle Roots of the batches, since those 3 needs to be changed together. We also locked with it the aggregation service, since it was having some concurrency issues, and since it's fast using it sequentially isn't a problem. 

- We have added a timeout for the Bls Aggregation service when a task response is received, since it sometimes never returns

- We have added a retry with a delay when sending a batched task response to Eth, since it sometimes fails by saying the batch doesn't exist, when it in fact exists. This may be due to the node not having the data yet.

- We removed a data structure that was not used, and added unnecesary code that generates confusion

- We moved all the checks in AddNewTask to the beggining, since it could happen that it mutates the aggregator state partially, because at a later point a check failed, leading to a failure of the aggregator

- We have improved the logging, and changed the errors to be warning or errors depending on if the error implies that the system fail or lost a batch, or that something may be wrong but the system is not sure

This closes #319

### CODE REVIEW

File: aggregator/internal/pkg/aggregator.go [hunk 1]
```diff
@@ -28,10 +28,7 @@ const QUORUM_NUMBER = byte(0)
...
 
 // Aggregator stores TaskResponse for a task here
-type TaskResponsesWithStatus struct {
-	taskResponses       []types.SignedTaskResponse
-	submittedToEthereum bool
-}
+type TaskResponses = []types.SignedTaskResponse
 
 type Aggregator struct {
 	AggregatorConfig      *config.AggregatorConfig
```
Comment (NicolasRampoldi) [inline aggregator/internal/pkg/aggregator.go:34]: test

**Review by MauroToscano — APPROVED** [review]

File: aggregator/internal/pkg/aggregator.go [hunk 2]
```diff
@@ -206,70 +196,76 @@ func (agg *Aggregator) sendAggregatedResponseToContract(blsAggServiceResp blsagg
...
 	// --- UPDATE BATCH - INDEX CACHES ---
-
-	agg.batchesRootByIdxMutex.Lock()
-	if _, ok := agg.batchesRootByIdx[batchIndex]; ok {
+	batchIndex := agg.nextBatchIndex
+	if _, ok := agg.batchesIdxByRoot[batchMerkleRoot]; ok {
 		agg.logger.Warn("Batch already exists", "batchIndex", batchIndex, "batchRoot", batchMerkleRoot)
-		agg.batchesRootByIdxMutex.Unlock()
+		agg.taskMutex.Unlock()
+		agg.AggregatorConfig.BaseConfig.Logger.Info("- Unocked Resources: Adding new task")
```
Comment (entropidelic) [inline aggregator/internal/pkg/aggregator.go]:
```suggestion
		agg.AggregatorConfig.BaseConfig.Logger.Info("- Unocked Resources: Adding new task")
```
```suggestion
		agg.AggregatorConfig.BaseConfig.Logger.Info("- Unlocked Resources: Adding new task")
```

File: aggregator/internal/pkg/aggregator.go [hunk 3]
```diff
@@ -206,70 +196,76 @@ func (agg *Aggregator) sendAggregatedResponseToContract(blsAggServiceResp blsagg
...
-	agg.batchesRootByIdxMutex.Unlock()
 
-	agg.batchesIdxByRootMutex.Lock()
 	// This shouldn't happen, since both maps are updated together
-	if _, ok := agg.batchesIdxByRoot[batchMerkleRoot]; ok {
+	if _, ok := agg.batchesRootByIdx[batchIndex]; ok {
 		agg.logger.Warn("Batch already exists", "batchIndex", batchIndex, "batchRoot", batchMerkleRoot)
-		agg.batchesRootByIdxMutex.Unlock()
+		agg.taskMutex.Unlock()
+		agg.AggregatorConfig.BaseConfig.Logger.Info("- Unocked Resources: Adding new task")
```
Comment (entropidelic) [inline aggregator/internal/pkg/aggregator.go]:
```suggestion
		agg.AggregatorConfig.BaseConfig.Logger.Info("- Unlocked Resources: Adding new task")
```

File: aggregator/internal/pkg/aggregator.go [hunk 4]
```diff
@@ -206,70 +196,76 @@ func (agg *Aggregator) sendAggregatedResponseToContract(blsAggServiceResp blsagg
...
-	agg.nextBatchIndex = agg.nextBatchIndex + 1
-	agg.nextBatchIndexMutex.Unlock()
-
 	// FIXME(marian): When this errors, should we retry initializing new task? Logging fatal for now.
 	if err != nil {
 		agg.logger.Fatalf("BLS aggregation service error when initializing new task: %s", err)
 	}
+
+	agg.taskMutex.Unlock()
+	agg.AggregatorConfig.BaseConfig.Logger.Info("- Unocked Resources: Adding new task")
```
Comment (entropidelic) [inline aggregator/internal/pkg/aggregator.go]:
```suggestion
	agg.AggregatorConfig.BaseConfig.Logger.Info("- Unlocked Resources: Adding new task")
```

File: aggregator/internal/pkg/server.go [hunk 5]
```diff
@@ -43,35 +45,57 @@ func (agg *Aggregator) ServeOperators() error {
 //   - 0: Success
 //   - 1: Error
 func (agg *Aggregator) ProcessOperatorSignedTaskResponse(signedTaskResponse *types.SignedTaskResponse, reply *uint8) error {
-
-	agg.AggregatorConfig.BaseConfig.Logger.Info("New task response", "taskResponse", signedTaskResponse)
-
-	if _, ok := agg.OperatorTaskResponses[signedTaskResponse.BatchMerkleRoot]; !ok {
+	agg.AggregatorConfig.BaseConfig.Logger.Info("New task response",
```
Comment (entropidelic) [inline aggregator/internal/pkg/server.go:48]: not really important for now but we should use directly `agg.Logger`. We can make an issue for solving this later in all the code

**Review by entropidelic — APPROVED** [review]

**Comment by entropidelic** [comment]
lgmt
